# Generated by Django 5.1.4 on 2025-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(default='uploads/Default_user_img.png', upload_to='uploads/'),
        ),
    ]
