# Generated by Django 5.1.4 on 2025-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(default='media/uploads/Default_user_img.png', upload_to='media/uploads/'),
        ),
    ]
