# Generated by Django 5.1.4 on 2025-03-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_range_per_night',
            field=models.CharField(default=300, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app_main.hotel')),
            ],
        ),
    ]
