# Generated by Django 5.1.7 on 2025-03-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_details', to='app_main.hotel')),
            ],
        ),
    ]
