# Generated by Django 5.1.7 on 2025-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_hotellocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='was_paid',
            field=models.BooleanField(default=False),
        ),
    ]
