# Generated by Django 5.1.7 on 2025-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_hotelreservation_was_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=199, max_digits=10),
            preserve_default=False,
        ),
    ]
