# Generated by Django 5.1.7 on 2025-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='contact',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
